version: '2'

linters:
  enable:
    - gocritic
    - govet
    - staticcheck
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - goimports
    - gofmt

run:
  timeout: 3m
  tests: true