app:
  name: 'url-shortener'
  version: '1.0.0'

http:
  port: '8080'

log:
  level: 'debug'

postgres:
  pool_max: 15

alias:
  # Для приведённой ниже конфигурации будет доступно 63^10 ~ 9.84 * 10^17 (984 квадриллиона) комбинаций.
  # Соответственно, вероятность коллизии вычисляем как количество записей в таблице, делённое на количество комбинаций.
  # Чтобы вероятность превысила хотя бы 20%, наша таблица должна содержать 1.968 * 10^17 записей.
  # Каждая запись занимает примерно 412 байт (11 на токен, 401 на ссылку
  # (возьмём среднюю длину 100 символов и 4 байта на символ)).
  # База с таким количеством записей будет весить примерно 73 млн терабайт.
  alphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_'
  length: 10

shortening:
  attempts: 5