# This workflow will generate an OpenAPI/Swagger specification.

name: Generate Swagger Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install swaggo/swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger Docs And Format Comments
      run: make swag

    - name: Commit Swagger Docs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update Swagger docs and formatting" || echo "No changes"
        git push