# This workflow will generate an OpenAPI/Swagger specification.

name: Generate Swagger Docs

on:
  push:
    branches: [ "main" ]
    paths: [ "internal/controller/**", "internal/app/app.go" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "internal/controller/**", "internal/app/app.go" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod tidy

    - name: Generate Swagger Docs And Format Comments
      run: |
        touch .env
        make swag

    - name: Commit Swagger Docs
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add /docs /internal
        git commit -m 'Update Swagger docs and formatting' || echo 'No changes'
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}